### ISSUE TITLE
SSI updates- add bip 39 generation, expose DID generation on header file

### ISSUE THREAD

**Issue by fkim7** [knox-networks/ssi#135]
part of https://github.com/knox-networks/dart-sdk/issues/62 realized some functions arent exposed in the SSI FFI header file.

Gaps identified so far
- bip 39 generation
- DID generation 
- VC download
- Wallet association

Until this is sorted out, Yan is going straight grpc

**Comment by LuisOsta** [comment]
@fkim7 Currently SSI doesn't support

- Getting VCs from credential adapter
- Wallet Association for user-mgmt

So we'd have to add that functionality here if we wanted to abstract that away for clients. Would we want add that functionality to SSI? @fkim7 @yanctrindade I'm curious to hear what the benefit is to handle it here vs in Dart. I'm not necessarily against it just curious to hear about what the benefits are.

The rest I think are FFI issues that I'll investigate

**Comment by LuisOsta** [comment]
@fkim7 For context "DID generation" is already exposed via `create_identity` and `registry_create_did`

**Comment by LuisOsta** [comment]
I've created https://github.com/knox-networks/ssi/issues/139 to handle the VC download side of thigns

**Comment by fkim7** [comment]
lets create link account/associate wallet also

**Comment by yanctrindade** [comment]
@LuisOsta the new KeyParir Struct expose the mnemonic but DidDocument has the DID after create_identity is not accessible since we dont have DidDocument struct exposed on ssi_ffi.h, something else we can do is create a fuction passing the didDocument pointer that returns the pointer.char to did generated. Idk the pros and cons from each approach.

The thing is, If I use only SSI lib I have following use cases

1. generate bip39 mnemonic and access the 12 words string
2. Create identity (DidDocumento struct)
3. registry the identity created (push did doc)

but If I want to access the did itself its not exposed from ssi_ffi.h
