### ISSUE TITLE
Implement create_data_integrity_proof for VerifiableCredential in SSI library

### ISSUE THREAD

**Issue by sKudryashov** [knox-networks/ssi#17]
Implement `create_data_integrity_proof` for `VerifiableCredential` in `SSI` library using specification: https://www.notion.so/Create-Integrate-Core-SSI-Rust-Library-Design-9eb9e58093a04a7d84bb476ac0324a7d#9ae9eb4daaba48a9a430cfd5146dac1a

**Comment by LuisOsta** [comment]
Once this issue is closed we need to:
- [ ] Create an issue to integrate DIDVerifier trait in the DynamicVerifier struct in Interbank
- [ ] Create an issue to integrate DIDSigner trait in the DynamicSigner struct in Interbank
You can find the current implementations here - https://github.com/monetae/core/blob/f4ef10f5c169a11f5eaf79317751e29b109b3b74/promissory/src/dynamic_signature.rs#L340-L343
