### ISSUE TITLE
Add `KeyPair` trait & `SSIKeyPair` struct in `signature` package.

### ISSUE THREAD

**Issue by LuisOsta** [knox-networks/ssi#39]
The trait should implement the following functions:
```
get_public_key(relation SignerRelation)
get_private_key(relation SignerRelation)
```

It should be purely informational. And then we should add functionality to our SSI Signer that converts a SSIKeyPair into a Signer

**Comment by fkim7** [comment]
After talking to Sergey, it seems supporting a generic signer instead of the current working ed25519 signer will be difficult.  Want to revisit this after, especially as we currently have everything dependent on ed25519 and if we need to add support for more signature types ex Secp256k1, we'll need to update all the components including interbank to make it work.  Will go with the ed25519 signer for the short term.
